# Generated by Django 5.2.6 on 2025-09-19 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=512, unique=True)),
                ('token_type', models.CharField(choices=[('password_reset', 'Password Reset'), ('email_verification', 'Email Verification'), ('account_activation', 'Account Activation')], default='password_reset', max_length=20)),
                ('generated_date', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('valid', models.BooleanField(default=True)),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Validation Token',
                'verbose_name_plural': 'Validation Tokens',
                'db_table': 'authentication_validationtoken',
                'ordering': ['-generated_date'],
            },
        ),
    ]
