# Generated by Django 5.2.6 on 2025-09-19 21:53

import django.db.models.deletion
import django.utils.timezone
import locations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=locations.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(help_text='Name or description of the location', max_length=255)),
                ('address', models.TextField(help_text='Full address of the location')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('investigating', 'Investigating'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='reported', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of the power outage')),
                ('estimated_customers_affected', models.PositiveIntegerField(blank=True, null=True)),
                ('reporter_contact', models.CharField(blank=True, help_text='Contact info if different from reporter', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('estimated_restoration', models.DateTimeField(blank=True, null=True)),
                ('actual_restoration', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['admin', 'team_lead', 'team_member']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_locations', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'reporter'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'db_table': 'locations_location',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.CharField(default=locations.models.generate_uuid, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('update_type', models.CharField(choices=[('status_change', 'Status Change'), ('assignment', 'Assignment'), ('priority_change', 'Priority Change'), ('general_update', 'General Update')], default='general_update', max_length=20)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(help_text='Update notes or comments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='locations.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Location Update',
                'verbose_name_plural': 'Location Updates',
                'db_table': 'locations_locationupdate',
                'ordering': ['-created_at'],
            },
        ),
    ]
